name: smart_ix
description: smart_ix home assistance.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^1.22.0
  firebase_auth: ^3.8.0
  cloud_firestore: ^3.4.8
  equatable: ^2.0.5
  google_sign_in: ^5.4.1
  flow_builder: ^0.0.9
  flutter_bloc: ^8.1.1
  google_fonts: ^3.0.1
  flutter_svg: ^1.1.5
  json_annotation: ^4.6.0
  path_provider: ^2.0.11
  http: ^0.13.0
  formz: ^0.4.1
  google_nav_bar: ^5.0.6
  geolocator: ^9.0.1
  fake_cloud_firestore: ^1.3.1
  uuid: ^3.0.6
  font_awesome_flutter: ^10.2.1
  flutter_staggered_grid_view: ^0.6.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mocktail: ^0.3.0
  bloc_test: ^9.1.0
  build_runner: ^2.2.0
  json_serializable: ^6.3.1
  plugin_platform_interface: ^2.1.2

flutter:
  generate: true
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
